### ISSUE TITLE
Unexpected keyword argument 'embed_dim'

### ISSUE THREAD

**Issue by pjsample** [AlphonsG/EPIC-BBox-Cell-Tracking#10]
Hello, I ran into this error when trying to run the example command for cell tracking.

TypeError: CascadeRCNN: SwinTransformer: __init__() got an unexpected keyword argument 'embed_dim'

I followed the instructions for creating a new environment with a few modifications: installed Python 3.8 via conda (which installs pip 22, so I did not run `python -m pip install 'pip<21.3' -U`. I ran all of the other commands verbatim. 

I came across a similar issue here: https://github.com/open-mmlab/mmsegmentation/issues/752

Thanks, looking forward to trying this!

**Comment by AlphonsG** [comment]
Hello, 

Thank you for your interest in using the software. I've updated the installation instructions to rectify this error. In particular, the wrong version of mmdet was being installed, which has been fixed [here](https://github.com/AlphonsG/EPIC-BBox-Cell-Tracking/pull/11/commits/aef42e0d3b66ba76b904605932e35dfaf9cddadb#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L61-R63). I've also made other changes to the instructions that might've caused issues too. Please see the updated Readme [here](https://github.com/AlphonsG/EPIC-BBox-Cell-Tracking/pull/11/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) in the pull request for the changes. In your case with your existing install, running the following updated commands without performing a fresh install should work:

```
mim install mmdet git+https://github.com/AlphonsG/Swin-Transformer-Object-Detection
```
```
cd misc
epic tracking examples/input_image_sequence configs/demo_config.yaml --detect always --num-frames 10 --analyse --save-tracks --vis-tracks  --dets-min-score 0.75
```

The object detection may take a really long time on a system without a GPU but provided no errors are reported and the progress bar animation is playing, it should eventually finish running once started. If it is taking too long without a GPU, please let me know and I can provide a much more lightweight dataset to test on. 

Lastly, conda was previously used with EPIC but some difficulties arose with some of the dependencies, hence the reference to venv in the installation instructions. There are also plans to majorly update/improve EPIC and have it as a package available on PyPI as opposed to anaconda. But hopefully your conda-based install works and please reach out if you run into trouble. 

Hopefully this helps.

**Comment by pjsample** [comment]
Thanks for the update and that did correct the original issue, however I ran into two new problems. First, when running `mim install mmdet git+https://github.com/AlphonsG/Swin-Transformer-Object-Detection`, there is an error installing mmpycocotools:

```
gcc: error: pycocotools/_mask.c: No such file or directory
gcc: fatal error: no input files
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1
----------------------------------------
ERROR: Failed building wheel for mmpycocotools
```

I then tried to run the example anyway and encountered this error:
```
File "/home/ubuntu/anaconda3/envs/epic_cpu/bin/epic", line 33, in <module>
    sys.exit(load_entry_point('epic', 'console_scripts', 'epic')())

  File "/data/EPIC-BBox-Cell-Tracking/epic/__main__.py", line 6, in main
    cli()

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)

  File "/data/EPIC-BBox-Cell-Tracking/epic/tracking/track.py", line 113, in track
    for input_dir in detect.callback(
            root_dir, yaml_config, vis_tracks, True, num_frames=num_frames,
            motchallenge=motchallenge, iterate=True,
            multi_sequence=multi_sequence, always=always):

  File "/data/EPIC-BBox-Cell-Tracking/epic/detection/detect.py", line 75, in detect
    detector = det_fcty.get_detector(detector_name, **config[detector_name])

  File "/data/EPIC-BBox-Cell-Tracking/epic/detection/detectors_factory.py", line 16, in get_detector
    return MMDetectionSwinTransformer.get_instance(**kwargs)

  File "/data/EPIC-BBox-Cell-Tracking/epic/detection/mmdetection_swin_transformer.py", line 57, in get_instance
    MMDetectionSwinTransformer(**kwargs)

  File "/data/EPIC-BBox-Cell-Tracking/epic/detection/mmdetection_swin_transformer.py", line 51, in __init__
    self.model = init_detector(config, checkpoint, device=device)

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/mmdet/apis/inference.py", line 42, in init_detector
    checkpoint = load_checkpoint(model, checkpoint, map_location=map_loc)

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 531, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 470, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 249, in load_checkpoint
    return checkpoint_loader(filename, map_location)

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/mmcv/runner/checkpoint.py", line 266, in load_from_local
    checkpoint = torch.load(filename, map_location=map_location)

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)

  File "/home/ubuntu/anaconda3/envs/epic_cpu/lib/python3.8/site-packages/torch/serialization.py", line 762, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
     |-> pickle_module.load = <built-in function load>
     |-> f = <_io.BufferedReader name='../misc/checkpoints/mmdetection_swin_transformer/wrd_epoch_100.pth'>
     |-> pickle_load_args = {'encoding': 'utf-8'}
_pickle.UnpicklingError: invalid load key, 'v'.
```

**Comment by AlphonsG** [comment]
I think the second error is a result of the first one. Please try running `pip install cython` then `mim install mmdet git+https://github.com/AlphonsG/Swin-Transformer-Object-Detection` again.

**Comment by pjsample** [comment]
I did two things that fixed the first problem with `mmpycocotools` -- I'm not sure which one did it. First, I built an environment with venv rather than conda (probably this one?). Second, I deleted the files in `/home/ubuntu/.cache/mim/`, thinking that the installation may have defaulted to cached versions rather than the changes specified in your installation instruction updates.

As I was typing this you replied with the comment above. It looks like cython is fine with my new environment. When I run `pip install cython` it returns:
```
Requirement already satisfied: cython in /data/envs/epic-env/lib/python3.8/site-packages (0.29.30)
```

`mim install mmdet git+https://github.com/AlphonsG/Swin-Transformer-Object-Detection` also return `Requirement already satisfied`. However, running the example command returned the same error, invalid load key, 'v'.

**Comment by AlphonsG** [comment]
Alright good to hear the first issue is resolved, I suspect it's venv too.

As for the second issue, may you please report if the file ../misc/checkpoints/mmdetection_swin_transformer/wrd_epoch_100.pth exists and it's file size?

**Comment by pjsample** [comment]
It does exists and it is 135 bytes.
Contents:
```
version https://git-lfs.github.com/spec/v1
oid sha256:b245a59c3dd1838f67c18e25deafe8b16cd7afef59180a8572af296237184260
size 1630884826
```

**Comment by AlphonsG** [comment]
Alright thanks. Seems like the checkpoint file wasn't downloaded. Please `cd` to this repo's root directory then download and install [git lfs](https://git-lfs.github.com/) (which includes performing step 1 on the linked page inside the root directory of this repo). Then run `git lfs pull` in this repo's root folder, this should download the checkpoint. Afterwards, please confirm that the checkpoint file is now at least a 1 GB in size then try running the example command again. I'll update the installation instructions with the git-lfs step.

Also, please remember to run the example command in the misc folder now as opposed to the epic folder of the old instructions.

**Comment by pjsample** [comment]
That was the issue and it's now working as expected. Thanks!

**Comment by AlphonsG** [comment]
Great to hear!
